# 敏感信息参数配置模板
# 注: secret.config.yaml 为敏感信息配置文件，不会上传到git仓库
# secret.config.yaml由本文件复制而来，填写敏感信息后，将本文件重命名为secret.config.yaml


# 每个网站一个观察者, 每个观察者带一个邮箱列表用以通知
# 观察者名字"name"对应配置文件"name.target.yaml"
observers:
  scut:
    - xxxx@xxx.xxxx


# 邮件发送配置
email:
  # 脚本发送邮件使用账号
  sender: xxxx@xx.xxx
  # 授权码
  passwd: xxxxxxx
  # 设置服务器参数
  # SSL加密的SMTP
  SMTP_SSL_ON: FALSE
  SMTP_SSL:
    host: smtp.xxx.xxx
    port: 465
  # TLS加密的SMTP
  SMTP_TLS_ON: TRUE
  SMTP_TLS:
    host: smtp.xxx.xxx
    port: 587


